# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xw5vmaFb8ZtKvBnrArtifQIaL7JXYPL3
"""

import nltk
from nltk.chat.util import Chat,reflections
pairs=[
    [
        r"my name is adesh",
        [" hi adesh,nice to hear you ,how can i help you"]
    ],
    [
        r"what is your name",
        ["my name is getchat"]
    ],
    [
        r"how are you",
        ["i am fine,how are you"]
    ],
    [
        r"i am fine",
        ["nice to hear that"]
    ],
    [
        r"who is your favorite sportsperson",
        ["M.S.Dhoni is my favorite cricket player,(the man,the mahi,the legend)"]
    ],
    [
        r"quit",
        ["thank you for using our application"]
    ],
]

def chat():
  chat=Chat(pairs)
  chat.converse()

if __name__=="__main__":
  chat()